name: cashen
description: 個人開発 / cashen
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.1.0
  flutter_launcher_icons: any
  # $ flutter pub pub run flutter_launcher_icons:main
  expansion_tile_card: ^2.0.0
  hooks_riverpod: ^0.14.0+4
  provider: ^5.0.0
  syncfusion_flutter_calendar: ^19.2.59
  firebase_analytics: ^8.3.4
  firebase_auth: ^3.1.4
  firebase_core: ^1.8.0
  cloud_functions: ^3.0.5
  firebase_storage: ^10.0.6

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
    - assets/fonts/
  fonts:
    - family: MPLUSRounded
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Medium.ttf

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icons/appstore.png"
  image_path_android: "assets/icons/appstore.png"
  adaptive_icon_foreground: "assets/icons/appstore.png"
  adaptive_icon_background: "assets/icons/appstore.png"

